### ISSUE TITLE
Update documentation to reflect new mobile testing

### ISSUE THREAD

**Issue by denschub** [mozilla/webcompat-addon#54]
web-ext requires that you specify the target device explicitly, which is not mentioned in the docs. Also, with the addition of `about:compat`, running `web-ext` alone is not an option if you want to test everything, as the only way to test `about:compat` is to run a local Fennec build.

Documentation needs some updates for that.

**Comment by rbrishabh** [comment]
Can I do this? Just let me know where I need to add the relevant documentation,
