### ISSUE TITLE
Consider tagging releases?

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-addon#85]
It would be nice to indicate we have a new version, and be able to compare to older ones -- tags are a good way to do this. Have we considered this?

**Comment by denschub** [comment]
Now that we have a somewhat reliable process for getting updates merged into central without lots of external dependencies, this would be a simple thing to add to our "how to release things" checklist. +1 from me.

**Comment by denschub** [comment]
To follow up, I [just tagged `v8.0.0`](https://github.com/mozilla/webcompat-addon/releases/tag/v8.0.0) and added a comment to the intervention release process doc. If we decide against tagging, that's also fine and I'm happy to remove the tag again, but I figured now is a good time to either make this part of our process - or to decide it won't be part of it.

**Comment by miketaylr** [comment]
We're doing this now! Thanks.
